"""Buffer table

Revision ID: 1dc4a67879ca
Revises: 251b9bc56d33
Create Date: 2020-03-21 12:50:19.373912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dc4a67879ca'
down_revision = '251b9bc56d33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buffer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_tag', sa.String(), nullable=False),
    sa.Column('duration', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['event_tag'], ['tag.tag_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buffer_event_tag'), 'buffer', ['event_tag'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_buffer_event_tag'), table_name='buffer')
    op.drop_table('buffer')
    # ### end Alembic commands ###
