"""Change rating date unique=False, and change couple str lengths

Revision ID: 2723223ae531
Revises: 5b64ace08c6e
Create Date: 2020-06-04 09:38:31.123645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2723223ae531'
down_revision = '5b64ace08c6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('buffer', 'event_tag',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=1000),
               existing_nullable=False)
    op.alter_column('event', 'story',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=False)
    op.alter_column('tag', 'tag_name',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.drop_constraint('date', 'rating', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tag', 'tag_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
    op.alter_column('event', 'story',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.alter_column('buffer', 'event_tag',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
    op.create_unique_constraint("date", "rating", ["date"])
    # ### end Alembic commands ###
