"""empty message

Revision ID: 2b97d043f02e
Revises: 251b9bc56d33
Create Date: 2020-03-21 14:47:57.186532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b97d043f02e'
down_revision = '251b9bc56d33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buffer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_tag', sa.String(), nullable=False),
    sa.Column('duration', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buffer_event_tag'), 'buffer', ['event_tag'], unique=False)
    op.create_index(op.f('ix_buffer_user_id'), 'buffer', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_buffer_user_id'), table_name='buffer')
    op.drop_index(op.f('ix_buffer_event_tag'), table_name='buffer')
    op.drop_table('buffer')
    # ### end Alembic commands ###
