"""add relationships, and rename tags --> events

Revision ID: 570707a32117
Revises: 89387e5b3451
Create Date: 2019-08-04 09:46:13.314720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '570707a32117'
down_revision = '89387e5b3451'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('rating_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['rating_date'], ['rating.date'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_rating_date'), 'event', ['rating_date'], unique=False)
    op.drop_table('tags')
    op.drop_table('tagmap')
    op.create_index(op.f('ix_rating_rating_sleep'), 'rating', ['rating_sleep'], unique=False)
    op.create_index(op.f('ix_rating_user_id'), 'rating', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_rating_user_id'), table_name='rating')
    op.drop_index(op.f('ix_rating_rating_sleep'), table_name='rating')
    op.create_table('tagmap',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tag_id', sa.INTEGER(), nullable=True),
    sa.Column('rating_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['rating_id'], ['rating.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tag', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag')
    )
    op.drop_index(op.f('ix_event_rating_date'), table_name='event')
    op.drop_table('event')
    op.drop_table('tag')
    # ### end Alembic commands ###
