"""Added a story column

Revision ID: 7a6560c1aced
Revises: dc1a2b164313
Create Date: 2020-04-08 15:31:45.260007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a6560c1aced'
down_revision = 'dc1a2b164313'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('rating_date', sa.DateTime(), nullable=False),
    sa.Column('story', sa.String(), nullable=False),
    sa.Column('event_tag', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['event_tag'], ['tag.tag_name'], ),
    sa.ForeignKeyConstraint(['rating_date'], ['rating.date'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_event_tag'), 'event', ['event_tag'], unique=False)
    op.create_index(op.f('ix_event_rating_date'), 'event', ['rating_date'], unique=False)
    op.create_index(op.f('ix_event_story'), 'event', ['story'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_story'), table_name='event')
    op.drop_index(op.f('ix_event_rating_date'), table_name='event')
    op.drop_index(op.f('ix_event_event_tag'), table_name='event')
    op.drop_table('event')
    # ### end Alembic commands ###
