"""add many to many support (not complete)

Revision ID: 89387e5b3451
Revises: bb0c7b1da9f2
Create Date: 2019-07-23 08:49:17.804939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89387e5b3451'
down_revision = 'bb0c7b1da9f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag')
    )
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('rating_sleep', sa.Integer(), nullable=False),
    sa.Column('meditation', sa.Integer(), nullable=False),
    sa.Column('cw', sa.Integer(), nullable=False),
    sa.Column('screen', sa.Time(), nullable=False),
    sa.Column('rating_day', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('tagmap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('rating_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rating_id'], ['rating.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tagmap')
    op.drop_table('rating')
    op.drop_table('tags')
    # ### end Alembic commands ###
