"""associations tables

Revision ID: b3934d6b3b53
Revises: 7a6560c1aced
Create Date: 2020-04-08 17:41:45.517032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3934d6b3b53'
down_revision = '7a6560c1aced'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_tags',
    sa.Column('event.id', sa.Integer(), nullable=True),
    sa.Column('tag.id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event.id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['tag.id'], ['event.id'], )
    )
    op.create_table('rating_events',
    sa.Column('rating_id', sa.Integer(), nullable=True),
    sa.Column('event.id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event.id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['rating_id'], ['rating.id'], )
    )
    op.drop_index('ix_event_event_tag', table_name='event')
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_column('event', 'event_tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('event_tag', sa.VARCHAR(), nullable=False))
    op.create_foreign_key(None, 'event', 'tag', ['event_tag'], ['tag_name'])
    op.create_index('ix_event_event_tag', 'event', ['event_tag'], unique=False)
    op.drop_table('rating_events')
    op.drop_table('event_tags')
    # ### end Alembic commands ###
