"""added unique to buffer/buffer_edit event_tag

Revision ID: bf563d47dc88
Revises: c23a5b4d5419
Create Date: 2020-06-11 19:21:54.677910

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf563d47dc88'
down_revision = 'c23a5b4d5419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buffer_edits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_tag', sa.String(length=2000), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buffer_edits_event_tag'), 'buffer_edits', ['event_tag'], unique=True)
    op.create_index(op.f('ix_buffer_edits_user_id'), 'buffer_edits', ['user_id'], unique=False)
    op.alter_column('buffer', 'event_tag',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1000),
               type_=sa.String(length=2000),
               existing_nullable=False)
    op.drop_index('ix_buffer_event_tag', table_name='buffer')
    op.create_index(op.f('ix_buffer_event_tag'), 'buffer', ['event_tag'], unique=True)
    op.alter_column('event', 'story',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1000),
               type_=sa.String(length=2000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'story',
               existing_type=sa.String(length=2000),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1000),
               existing_nullable=False)
    op.drop_index(op.f('ix_buffer_event_tag'), table_name='buffer')
    op.create_index('ix_buffer_event_tag', 'buffer', ['event_tag'], unique=False)
    op.alter_column('buffer', 'event_tag',
               existing_type=sa.String(length=2000),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1000),
               existing_nullable=False)
    op.drop_index(op.f('ix_buffer_edits_user_id'), table_name='buffer_edits')
    op.drop_index(op.f('ix_buffer_edits_event_tag'), table_name='buffer_edits')
    op.drop_table('buffer_edits')
    # ### end Alembic commands ###
