"""rating_table_unique_constraints_date_user_id

Revision ID: c23a5b4d5419
Revises: 2723223ae531
Create Date: 2020-06-05 14:50:34.074566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c23a5b4d5419'
down_revision = '2723223ae531'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('date_userid', 'rating', ['date', 'user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('date_userid', 'rating', type_='unique')
    # ### end Alembic commands ###
